// <auto-generated />
using System;
using Depences.Infrastructure.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Depences.Infrastructure.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    partial class DefaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Depences.Infrastructure.Implementation.DataModels.DepenceEntity", b =>
                {
                    b.Property<int?>("DepenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("DepenceId"));

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DepenceDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Montant")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("NatureId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DepenceId");

                    b.HasIndex("NatureId");

                    b.HasIndex("UserId");

                    b.ToTable("Depences", "DEP");
                });

            modelBuilder.Entity("Depences.Infrastructure.Implementation.DataModels.DeviseEntity", b =>
                {
                    b.Property<int>("DeviseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviseId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeviseId");

                    b.ToTable("Devises", "DEP");

                    b.HasData(
                        new
                        {
                            DeviseId = 1,
                            Code = "USD"
                        },
                        new
                        {
                            DeviseId = 2,
                            Code = "RUS"
                        });
                });

            modelBuilder.Entity("Depences.Infrastructure.Implementation.DataModels.NatureEntity", b =>
                {
                    b.Property<int>("NatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NatureId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NatureId");

                    b.ToTable("Natures", "DEP");

                    b.HasData(
                        new
                        {
                            NatureId = 1,
                            Code = "Restaurant"
                        },
                        new
                        {
                            NatureId = 2,
                            Code = "Hotel"
                        },
                        new
                        {
                            NatureId = 3,
                            Code = "Misc"
                        });
                });

            modelBuilder.Entity("Depences.Infrastructure.Implementation.DataModels.UserDeviseEntity", b =>
                {
                    b.Property<int>("UserDeviseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserDeviseId"));

                    b.Property<int?>("DeviseId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserDeviseId");

                    b.ToTable("UserDevis", "DEP");

                    b.HasData(
                        new
                        {
                            UserDeviseId = 1,
                            DeviseId = 1,
                            UserId = 1
                        },
                        new
                        {
                            UserDeviseId = 2,
                            DeviseId = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Depences.Infrastructure.Implementation.DataModels.UserEntity", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("DeviseId")
                        .HasColumnType("int");

                    b.Property<string>("NomFamille")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("DeviseId");

                    b.ToTable("Users", "DEP");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DeviseId = 1,
                            NomFamille = "Stark",
                            Prenom = "Anthony"
                        },
                        new
                        {
                            UserId = 2,
                            DeviseId = 2,
                            NomFamille = "Romanova",
                            Prenom = "Natasha"
                        });
                });

            modelBuilder.Entity("Depences.Infrastructure.Implementation.DataModels.DepenceEntity", b =>
                {
                    b.HasOne("Depences.Infrastructure.Implementation.DataModels.NatureEntity", "Nature")
                        .WithMany()
                        .HasForeignKey("NatureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Depences.Infrastructure.Implementation.DataModels.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Nature");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Depences.Infrastructure.Implementation.DataModels.UserEntity", b =>
                {
                    b.HasOne("Depences.Infrastructure.Implementation.DataModels.DeviseEntity", "Devise")
                        .WithMany()
                        .HasForeignKey("DeviseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Devise");
                });
#pragma warning restore 612, 618
        }
    }
}
